'use client'
import { useState } from 'react'
import { money } from '@/lib/daily-sales-report'
import styles from './report.module.css'
const palette=['#4f6de0','#9270cf','#31a2ad','#e4a04d','#dc7d9b','#6788a8']
export default function ContributionChart({contributors}:{contributors:{agent:string;sales:number}[]}){
 const [selected,setSelected]=useState<string|null>(null),[hovering,setHovering]=useState(false)
 const total=contributors.reduce((n,r)=>n+r.sales,0),active=contributors.find(r=>r.agent===selected)
 const circumference=2*Math.PI*94
 return <aside className={styles.chart}><span className={styles.eyebrow}>SALES CONTRIBUTION</span><h2>Sales by contributor</h2><button className={styles.allContributors} aria-pressed={!active} onClick={()=>{setSelected(null);setHovering(false)}}>All contributors · {money(total)}</button><p>Hover or tap an agent · sales in INR</p><div className={styles.interactiveDonut} onMouseLeave={()=>setHovering(false)}>
 <svg viewBox="0 0 260 260" aria-label="Sales contribution by employee" role="group"><circle cx="130" cy="130" r="94" fill="none" stroke="#e7ecf7" strokeWidth="30"/>{contributors.map((r,i)=>{const fraction=r.sales/total,offset=contributors.slice(0,i).reduce((n,x)=>n+x.sales,0)/total;const angle=(offset+fraction/2)*2*Math.PI-Math.PI/2;return <g key={r.agent}><circle cx="130" cy="130" r="94" fill="none" stroke={palette[i%palette.length]} strokeWidth={active?.agent===r.agent?36:30} strokeDasharray={`${Math.max(circumference*fraction*.65,circumference*fraction-2)} ${circumference}`} strokeDashoffset={-circumference*offset} transform="rotate(-90 130 130)" tabIndex={0} role="button" aria-label={`${r.agent}, ${money(r.sales)}, ${(fraction*100).toFixed(1)}%`} onMouseEnter={()=>{setSelected(r.agent);setHovering(true)}} onFocus={()=>{setSelected(r.agent);setHovering(true)}} onBlur={()=>setHovering(false)} onClick={()=>{setSelected(r.agent);setHovering(true)}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(r.agent);setHovering(true)}}}><title>{`${r.agent} · ${money(r.sales)} · ${(fraction*100).toFixed(1)}%`}</title></circle>{fraction<.02&&<line x1={130+109*Math.cos(angle)} y1={130+109*Math.sin(angle)} x2={130+128*Math.cos(angle)} y2={130+128*Math.sin(angle)} stroke={palette[i%palette.length]}/>}<text style={fraction<.02?{fill:palette[i%palette.length],stroke:'white'}:undefined} x={130+(fraction<.02?138:94)*Math.cos(angle)} y={130+(fraction<.02?138:94)*Math.sin(angle)} textAnchor="middle" dominantBaseline="middle" className={styles.segmentPercent}>{(fraction*100).toFixed(1)}%</text></g>})}</svg>
 <div className={styles.donutCenter}>{active?<><span>{hovering?'Selected employee':'Sales contributor'}</span><b>{active.agent}</b><strong>{money(active.sales)}</strong><small>{(active.sales/total*100).toFixed(1)}% contribution</small></>:<><span>ALL CONTRIBUTORS</span><b>Total sales</b><strong>{money(total)}</strong><small>{total>0?'100% contribution':'No sales'}</small></>}</div>
 {hovering&&active&&<div role="tooltip" className={styles.chartTooltip}><b>{active.agent}</b><span>{money(active.sales)} · {(active.sales/total*100).toFixed(1)}%</span></div>}</div>
 <div className={styles.contributionHeader}><span>Employee</span><span>Total (INR)</span><span>Contribution</span></div><div className={styles.legend}>{contributors.map((r,i)=><button key={r.agent} aria-pressed={active?.agent===r.agent} onMouseEnter={()=>{setSelected(r.agent);setHovering(true)}} onMouseLeave={()=>setHovering(false)} onFocus={()=>{setSelected(r.agent);setHovering(true)}} onBlur={()=>setHovering(false)} onClick={()=>setSelected(r.agent)}><i style={{background:palette[i%palette.length]}}/><span>{r.agent}</span><strong>{money(r.sales)}</strong><b>{(r.sales/total*100).toFixed(1)}%</b></button>)}</div><div className={styles.contributionTotal}><b>Grand total</b><strong>{money(total)}</strong><b>{total>0?'100%':'—'}</b></div></aside>
}
