'use client'
import { useEffect, useRef, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, CalendarDays, ChevronDown, Download, RefreshCw, X } from 'lucide-react'
import { companies, dayLabel, money, scopedRows, exportSalesHTML, type Company, type DailySalesReport } from '@/lib/daily-sales-report'
import { callingSummary, showCount, employeeTotal, scopedEmployees } from '@/lib/daily-sales-calling'
import ContributionChart from './contribution-chart'
const todayIST=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
import { copyReportHTML, printReport, reportJPG, saveReportFile } from '@/lib/marketing-report-browser'
import styles from './report.module.css'

export default function DailySalesReportAlert(){
 const [date,setDate]=useState(todayIST),[scope,setScope]=useState('ALL'),[report,setReport]=useState<DailySalesReport|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const [dialog,setDialog]=useState<{kind:string;html:string;name:string;subject:string}|null>(null)
 const lock=useRef(false),closeButton=useRef<HTMLButtonElement>(null)
 function reload(nextDate=date){setLoading(true);setError('');setReport(null);setDialog(null);setDate(nextDate);setRetry(n=>n+1)}
 useEffect(()=>{const controller=new AbortController()
 fetch('/api/daily-sales-report-alert?date='+date,{cache:'no-store',signal:controller.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw Error(data.error||'Unable to load report');return data}).then(data=>{if(!controller.signal.aborted)setReport(data)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)})
 return()=>controller.abort()},[date,retry])
 useEffect(()=>{if(dialog)closeButton.current?.focus();const listener=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!lock.current)setDialog(null)};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener)},[dialog])
 const rows=report?scopedRows(report,scope):[],codes=scope==='ALL'?Object.keys(companies):[scope]
 const total=(key:'sales'|'unverified'|'cancelled'|'dialer'|'conversions')=>rows.reduce((n,r)=>n+r[key],0)
 const contributors=Object.values(rows.reduce<Record<string,{agent:string;sales:number}>>((acc,r)=>{const key=r.agent.toLowerCase();acc[key]??={agent:r.agent,sales:0};acc[key].sales+=r.sales;return acc},Object.create(null))).filter(r=>r.sales>0).sort((a,b)=>b.sales-a.sales)
 const totalSales=total('sales'),calling=report?.calling,summary=callingSummary(calling,scope),employees=scopedEmployees(calling,scope)
 async function action(kind:string){if(!report||lock.current)return;lock.current=true;setBusy(true);setNotice('')
 try{const html=exportSalesHTML(report,scope),name=`Daily-Sales-Report-${date}-${scope}`,subject=`Daily Sales Report Alert | ${dayLabel(date)} | ${scope==='ALL'?'All companies':companies[scope as Company]}`
 if(kind==='print')await printReport(html)
 else if(kind==='jpg'){saveReportFile(await reportJPG(html),name+'.jpg');setNotice('JPG downloaded')}
 else if(kind==='html'){saveReportFile(new Blob([html],{type:'text/html'}),name+'.html');setNotice('HTML downloaded')}
 else setDialog({kind,html,name,subject})
 }catch(e){setNotice(e instanceof Error?e.message:'Export unavailable')}finally{lock.current=false;setBusy(false)}}
 async function share(){if(!dialog||lock.current)return;lock.current=true;setBusy(true);try{const file=new File([await reportJPG(dialog.html)],dialog.name+'.jpg',{type:'image/jpeg'});if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:dialog.subject});else{saveReportFile(file,file.name);setNotice('JPG downloaded. Attach it in WhatsApp.')}}catch(e){setNotice(e instanceof Error?e.message:'Share unavailable')}finally{lock.current=false;setBusy(false)}}
 return <main className={styles.shell}>
  <nav className={styles.breadcrumb}><Link href="/sales/reports"><ArrowLeft size={15}/> Sales Report</Link><span>/ Daily Sales Report Alert</span></nav>
  <header className={styles.hero}><div className={styles.brand}>KAIRALI GROUP <span> / </span> DAILY SALES BRIEFING</div><div className={styles.heroTop}><div><h1>Daily Sales Report Alert</h1><p className={styles.date}><CalendarDays size={17}/>{dayLabel(date)} <small>IST</small></p><p className={styles.scope}>{scope==='ALL'?'All companies · Healing Village, Villa Raag & KAPPL':companies[scope as Company]}</p></div>
  <div className={styles.controls}><label>Report date<input aria-label="Report date" type="date" value={date} max={todayIST()} onChange={e=>{if(e.target.value)reload(e.target.value)}}/></label><label>Company<select aria-label="Company" value={scope} onChange={e=>{setScope(e.target.value);setDialog(null)}}><option value="ALL">All companies</option>{Object.entries(companies).map(([code,name])=><option key={code} value={code}>{code} · {name}</option>)}</select></label><details className={styles.menu}><summary><Download size={15}/>Export & Share<ChevronDown size={14}/></summary><div>{[['print','Print / Save PDF'],['jpg','Download JPG'],['html','Download HTML'],['email','Email template'],['whatsapp','WhatsApp share']].map(([kind,label])=><button key={kind} disabled={!report||loading||busy} onClick={e=>{e.currentTarget.closest('details')!.open=false;void action(kind)}}>{label}</button>)}</div></details></div></div>
  <div className={styles.heroStats}><div><span>SALES VALUE</span><strong>{report?money(totalSales):'—'}</strong><small>KTAHV by booking date</small></div><div><span>UNVERIFIED SALES</span><strong>{report?money(total('unverified')):'—'}</strong><small>Awaiting verification</small></div><div><span>CANCELLED VALUE</span><strong>{report?money(total('cancelled')):'—'}</strong><small>Reported separately</small></div><div><span>SALES CONTRIBUTORS</span><strong>{report?contributors.length:'—'}</strong><small>Agents with positive sales</small></div></div></header>
  <div className={styles.toolbar}><span><i/> {loading?'Loading SQL report…':report?'SQL connected · Partial calling coverage':'Report unavailable'}</span><button disabled={loading} onClick={()=>reload()}><RefreshCw size={14}/>Refresh</button></div>
  {report?.cancellationSnapshotAt&&<p className={styles.sourceNote}>KTAHV cancellation dates · Sheet snapshot {new Date(report.cancellationSnapshotAt).toLocaleString('en-GB',{timeZone:'Asia/Kolkata'})} IST</p>}
  {error&&<div role="alert" className={styles.coverage}>{error}</div>}
  {loading&&<div role="status" className={styles.loading}>Preparing the daily sales briefing…</div>}
  {report&&<><div className={styles.callingHeading}><h2>Calling overview</h2><p>Pending totals: {scope==='ALL'?'all companies':scope} · {calling?.pendingMode==='snapshot'?'Saved snapshot ·':'Live'} {calling?.pendingCapturedAt?new Date(calling.pendingCapturedAt).toLocaleString('en-GB',{timeZone:'Asia/Kolkata'}):'unavailable'} IST<br/>Calls done: Live sheet · {summary.dates.join(', ')||'unavailable'} · employee totals cover all companies</p></div>
  <div className={styles.metrics}>{[
 ['Pending leads (AppSheet)',showCount(summary.pendingAppsheet),'DialerPending · AppSheet total'],
 ['Pending leads National (Hopper)',showCount(summary.pendingNational),'DialerPending · National total'],
 ['Pending leads International (Hopper)',showCount(summary.pendingInternational),'DialerPending · International total'],
 ['Calls Done (AppSheet)',showCount(summary.appsheet),scope==='ALL'?'Live · column AI':'Company split not in Live sheet'],
 ['Calls Done National (Hopper)','—','National done split required'],
 ['Calls Done International (Hopper)','—','International done split required']
 ].map(([label,value,note],index)=><article key={label} className={index<3?styles.pendingMetric:styles.doneMetric}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</div>
  <section className={styles.company}><header><div><span className={styles.tag}>{scope==='ALL'?'ALL COMPANIES':scope}</span><h2>Employee calling activity</h2><p>Employees by registered company · Latest calling activity</p></div></header><div className={styles.tableScroll}><table className={styles.callingTable}><thead><tr><th rowSpan={2}>Employee</th><th colSpan={2} className={styles.appsheetGroup}>AppSheet</th><th className={styles.dialerGroup}>Dialer</th><th rowSpan={2} className={styles.doneGroup}>Total calls done</th><th rowSpan={2}>Last updated (IST)</th></tr><tr><th>Pending leads</th><th>Calls done</th><th>Calls done</th></tr></thead><tbody>{employees.map(r=><tr key={r.name}><td>{r.name}</td><td>{showCount(r.pending)}</td><td>{showCount(r.appsheet)}</td><td>{showCount(r.dialer)}</td><td className={styles.sale}>{showCount(r.done)}</td><td>{r.updatedAt}</td></tr>)}</tbody><tfoot><tr><td>Grand total</td>{(['pending','appsheet','dialer','done'] as const).map(key=><td key={key}>{showCount(employeeTotal(employees,key))}</td>)}<td>All employees</td></tr></tfoot></table></div>{!employees.length&&<p className={styles.empty}>No calling employees available for this company.</p>}</section>
  <div className={styles.content}><div className={styles.tables}>{codes.map(code=>{const agents=rows.filter(r=>r.company===code);return <section key={code} className={styles.company}><header><div><span className={styles.tag}>{code}</span><h2>{companies[code as Company]}</h2><p>Agent performance · {dayLabel(date)}</p></div><div className={styles.companyTotal}><span>Sales value</span><strong>{money(agents.reduce((n,r)=>n+r.sales,0))}</strong></div></header><div className={styles.tableScroll}><table><thead><tr>{['Agent name','Sales value','Cancelled value'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{agents.map(r=><tr key={r.agent}><td><span className={styles.avatar}>{r.agent.split(' ').map(x=>x[0]).slice(0,2).join('')}</span>{r.agent}</td><td className={r.sales>0?styles.sale:undefined}>{money(r.sales)}</td><td>{money(r.cancelled)}</td></tr>)}</tbody><tfoot><tr><td>Grand total</td><td>{money(agents.reduce((n,r)=>n+r.sales,0))}</td><td>{money(agents.reduce((n,r)=>n+r.cancelled,0))}</td></tr></tfoot></table></div>{!agents.length&&<p className={styles.empty}>No sales found for this date.</p>}</section>})}</div>
  <ContributionChart key={scope+date} contributors={contributors}/></div>
  <details className={styles.coverage}><summary>Data coverage & metric definitions <span>Source dates & coverage</span></summary><ul>{[...report.warnings,...(calling?.warnings||[])].map(w=><li key={w}>{w}</li>)}</ul><p>Sales: conversion_updates_employeewise · Calling: Master Report - Sales Calling / Live and DialerPending. Selected day runs midnight to midnight IST. No customer contact details are included.</p></details><footer className={styles.footer}>Prepared for Sales Team & Management <span>INR · IST · Updated {new Date(report.generatedAt).toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit'})} IST</span></footer></>}
  {notice&&!dialog&&<p role="status" className={styles.notice}>{notice}</p>}
  {dialog&&<div className={styles.backdrop}><section role="dialog" aria-modal="true" aria-labelledby="share-title" className={styles.dialog}><header><div><h2 id="share-title">{dialog.kind==='email'?'Email template':'WhatsApp report'}</h2><p>{dialog.subject}</p></div><button ref={closeButton} aria-label="Close preview" disabled={busy} onClick={()=>setDialog(null)}><X/></button></header><iframe title="Export preview" srcDoc={dialog.html} sandbox=""/><div className={styles.dialogActions}>{dialog.kind==='email'?<><button onClick={async()=>{try{await copyReportHTML(dialog.html);setNotice('Formatted email copied. Paste into your email composer.')}catch{setNotice('Clipboard unavailable. Download the HTML template.')}}}>Copy formatted email</button><button onClick={()=>saveReportFile(new Blob([dialog.html],{type:'text/html'}),dialog.name+'.html')}>Download email HTML</button></>:<button disabled={busy} onClick={share}>{busy?'Preparing image…':'Share / download JPG'}</button>}<button onClick={async()=>{try{await navigator.clipboard.writeText(dialog.subject);setNotice('Caption copied')}catch{setNotice('Clipboard unavailable')}}}>Copy caption</button></div><p role="status">{notice||'Preview includes the selected date, company scope and data coverage notes.'}</p></section></div>}
 </main>
}
