export interface MRFMSLead {
  timestamp: string
  verifiedDate: string
  id: string
  clientName: string
  mobileNumber: string
  email: string
  address: string
  pincode: string
  state: string
  city: string
  area: string
  clientType: string
  speciality: string
  clientCategory: string
  dataSource: string
  notes: string
  recordingUrl: string
  verifiedArea: string
  verifiedPincode: string
  leadOutcome: string
  remarks: string
  mrNameAsPerPincode: string
  existingNewAsPerMRData: string
  altMobileNumber: string
  callingSalesPersonName: string
  planned: string
  actual: string
  col28: string
  status: string
  assignToMROrASM: string
  remarksOps: string
  assignToTPDate: string
  partyType: string
  verifiedAreaTP: string
  helpTicketStatusToAssignPerson: string
  transferToApiSheetStatus: string
  directTransferToTpSheet: string
  col38: string
  altMobileNumberTP: string
  exceptions: string
  htStatusFromHtRecordSheet: string
  responseOfAddInApp: string
  responseOfTPUpdate: string
  transferToDeleteSheet: string
  transferToBufferStatusIfNoMRExist: string
}
