import { dashboard,type MonitorState } from './model'
const esc=(v:unknown)=>String(v??'Unknown').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))
export function renderTriggerDigest(state:MonitorState,origin:string,now=Date.now()){
 const d=dashboard(state,now),active=d.triggers.filter(t=>t.status!=='Removed'),failures=active.filter(t=>t.status==='Failed').length
 const success=active.reduce((n,t)=>n+t.success,0),failed=active.reduce((n,t)=>n+t.failed,0)
 const link=(href:string,label:string)=>`<a style="color:#4338ca;margin-right:14px" href="${esc(href)}">${esc(label)}</a>`
 const date=new Date(now).toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata'})
 const html=`<!doctype html><html><body style="margin:0;background:#f3f5fa;font:14px/1.6 Arial;color:#182537"><div style="max-width:900px;margin:24px auto;background:white;padding:28px"><h2 style="color:#4338ca">Kairali · Daily Trigger Health</h2><p>${esc(date)} · Last 24 hours · Asia/Kolkata</p><h3>${failures} failing triggers · ${active.length} monitored triggers</h3><p>${success} successful / ${failed} failed executions · Success: ${success+failed?(success/(success+failed)*100).toFixed(1)+'%':'No completed runs'}</p><p>Coverage: ${d.accounts.filter(a=>a.connected).length}/${d.accounts.length} Google accounts connected; ${d.projects.filter(p=>p.lastInventory).length}/${d.projects.length} projects have reported inventory. Bound projects require registration. Missing telemetry is not success.</p>${d.truncatedBefore?'<p>Retention limit reached; rates cover retained executions only.</p>':''}${d.accounts.map(a=>`<p><strong>${esc(a.email)}</strong> — ${a.connected?'Authorized':'Not connected'}; ${active.filter(t=>t.email===a.email).length} triggers; ${active.filter(t=>t.email===a.email&&t.status==='Failed').length} failed${a.scanError?'; '+esc(a.scanError):''}</p>`).join('')}<hr>${active.length?active.map(t=>`<section style="padding:18px 0;border-bottom:1px solid #e2e8f0"><h3 style="color:${t.status==='Failed'?'#b91c1c':'#334155'}">${esc(t.status)} · ${esc(t.sheetName||t.projectName)}</h3><p>Creator: ${esc(t.email)} · Sheet owner: ${esc(t.sheetOwner)}<br>Trigger ID: ${esc(t.triggerId)} · Function: ${esc(t.handler)} · Type: ${esc(t.type)}<br>Created: ${esc(t.createdAt||'Unavailable from Google')} · First discovered: ${esc(t.firstSeen)}<br>Latest run: ${esc(t.latest?.startedAt)} · Duration: ${t.latest?.durationMs===undefined?'Unknown':esc((t.latest.durationMs/1000).toFixed(1))+'s'}<br>24h success / failure: ${t.success} / ${t.failed} · ${t.successRate===null?'No completed runs':t.successRate.toFixed(1)+'% success'}<br>Consecutive failures: ${t.consecutiveFailures} · Developer: ${esc(t.assignee||'Unassigned')}</p><p><strong>Reason:</strong> ${esc(t.reason)}<br><strong>Suggested fix:</strong> ${esc(t.solution)}</p>${t.stale?'<p>Inventory heartbeat stale — check connector.</p>':''}${t.sheetUrl?link(t.sheetUrl,'Open sheet'):''}${link(t.scriptUrl,'Open script')}${link(t.logsUrl,'Execution logs')}${link(origin+'/settings/automation/trigger-management?trigger='+encodeURIComponent(t.key),'View incident')}</section>`).join(''):'<p>No trigger inventory received. Complete account/project onboarding before relying on this report.</p>'}<p>${link(origin+'/settings/automation/trigger-management','Open Trigger Management')}</p><p style="color:#64748b">Times above are ISO UTC unless labeled IST. Raw exception text and sheet cell data are excluded. Acknowledgment does not mark a trigger fixed; verify its next successful execution.</p></div></body></html>`
 return {html,failures,hasData:true}
}
