const assert=require('node:assert/strict')
const ts=require('typescript'),fs=require('node:fs'),Module=require('node:module')
function load(file){const m=new Module(file,module);m.filename=file;m.paths=module.paths;m.require=(id)=>id==='./marketing-report-query'?load(require('node:path').resolve('lib/marketing-report-query.ts')):require(id);m._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,file);return m.exports}
const {leakageParams,leakageQuery}=load(require('node:path').resolve('lib/good-lead-leakage.ts'))
assert.deepEqual(leakageParams('2026-09-01','2026-09-11','ALL','AI'),['2026-09-01','2026-09-12','ALL','ALL','AI','AI'])
for(const input of [['2026-02-30','2026-03-01','ALL','ALL'],['2026-09-11','2026-09-01','ALL','ALL'],['2026-01-01','2026-09-11','ALL','ALL'],['2026-09-01','2026-09-11',"' OR 1=1",'ALL'],['2026-09-01','2026-09-11','ALL','unknown']]) assert.throws(()=>leakageParams(...input))
assert(!/\b(INSERT|UPDATE|DELETE|ALTER|DROP)\b/i.test(leakageQuery))
console.log('PASS: date boundaries, range limit, filters, and read-only query')
if(process.argv.includes('--live')) (async()=>{require('@next/env').loadEnvConfig(process.cwd());const mysql=require('mysql2/promise');let c;try{c=await mysql.createConnection({host:process.env.DB_HOST,port:Number(process.env.DB_PORT||3306),user:process.env.DB_USER,password:process.env.DB_PASSWORD,database:process.env.DB_NAME,connectTimeout:10000});await c.query('START TRANSACTION READ ONLY');const [rows]=await c.query({sql:leakageQuery,timeout:20000},leakageParams('2026-09-01','2026-09-11','ALL','ALL'));assert(rows.every(r=>Number(r.reopened)<=Number(r.cold)&&Number(r.lowAttempts)<=Number(r.reopened)));for(const review of ['AI','Manual']){const [filtered]=await c.query({sql:leakageQuery,timeout:20000},leakageParams('2026-09-01','2026-09-11','ALL',review));assert.equal(filtered.reduce((a,r)=>a+Number(r.cold),0),rows.filter(r=>r.review===review).reduce((a,r)=>a+Number(r.cold),0))}console.log('PASS: live SQL executed, numeric invariants and review filter totals reconciled; no raw records printed');await c.rollback()}catch(e){console.error('FAIL:',e.code||e.message);process.exitCode=1}finally{await c?.end()}})()
