const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),ts=require('typescript'),vm=require('node:vm');
const now=Date.parse('2026-10-05T08:00:00.000Z'),email='sysadmin@example.com',scriptId='script_123456789',triggerId='12345';
const cache={};let apiState,apiWrites=0;
const sandboxEnv={NEXTAUTH_SECRET:'test-only-secret-that-is-longer-than-32-bytes',NEXT_PUBLIC_APP_URL:'https://crm.example.com'};
function load(file){file=path.resolve(file);if(cache[file])return cache[file].exports;const module={exports:{}};cache[file]=module;const req=id=>{
 if(id==='@/lib/authz'||id==='../authz')return {getSessionUser:req=>req.testUser||null};
 if(id==='@/lib/trigger-monitor/store')return {readMonitor:async()=>apiState,monitorTransaction:async fn=>{apiWrites++;return fn(apiState)}};
 if(id==='@/lib/trigger-monitor/google')return {scanAccount:async()=>({discovered:0})};
 if(id.startsWith('@/'))return load(id.slice(2)+'.ts');
 if(id.startsWith('.'))return load(path.resolve(path.dirname(file),id+'.ts'));
 return require(id)};
 const js=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2021,esModuleInterop:true}}).outputText;
 vm.runInNewContext(js,{module,exports:module.exports,require:req,process:{...process,env:sandboxEnv},Buffer,URL,console,Date,setTimeout});return module.exports}
const m=load('lib/trigger-monitor/model.ts'),security=load('lib/trigger-monitor/security.ts'),mail=load('lib/trigger-monitor/email.ts');
function setup(){const s=m.emptyState();s.accounts=[{email,addedAt:new Date(now).toISOString()}];const p={key:m.projectKey(email,scriptId),email,scriptId,name:'Stock tracker',discoveredAt:new Date(now).toISOString()};s.projects.push(p);m.applyIntake(s,p,inventory(),now);return {s,p}}
function inventory(at=now,items=[{triggerId,handler:'syncStock',type:'CLOCK'}]){return {kind:'inventory',email,scriptId,at:new Date(at).toISOString(),triggers:items}}
function execution(status='Success',runId='00000000-0000-4000-8000-000000000001',time=now-5000){return {kind:'execution',email,scriptId,triggerId,runId,startedAt:new Date(time).toISOString(),...(status==='Running'?{}:{finishedAt:new Date(time+1000).toISOString(),durationMs:1000}),status,reason:status==='Failed'?'quota':'none'}}
test('unobserved inventory has Unknown status and no invented success rate',()=>{const {s}=setup(),d=m.dashboard(s,now);assert.equal(d.triggers[0].status,'Unknown');assert.equal(d.triggers[0].successRate,null);assert.equal(d.triggers[0].createdAt,undefined)});
test('replayed start and completion are idempotent; delayed start cannot downgrade success',()=>{const {s,p}=setup();for(const e of [execution('Running'),execution(),execution(),execution('Running')])m.applyIntake(s,p,e,now);assert.equal(s.executions.length,1);assert.equal(s.executions[0].status,'Success')});
test('out-of-order inventory cannot remove or restore newer triggers',()=>{const {s,p}=setup();m.applyIntake(s,p,inventory(now+1000,[]),now+1000);m.applyIntake(s,p,inventory(now),now+1000);assert.ok(s.triggers[0].removedAt)});
test('different account cannot write a project',()=>{const {s,p}=setup();assert.throws(()=>m.applyIntake(s,p,{...inventory(),email:'attacker@example.com'},now),/identity mismatch/)});
test('unknown trigger execution is rejected',()=>{const {s,p}=setup();assert.throws(()=>m.applyIntake(s,p,{...execution(),triggerId:'missing'},now),/inventory/) });
test('failure rate uses completed runs only and stale running becomes unknown',()=>{const {s,p}=setup();m.applyIntake(s,p,execution('Success'),now);m.applyIntake(s,p,execution('Failed','00000000-0000-4000-8000-000000000002',now-3000),now);m.applyIntake(s,p,execution('Running','00000000-0000-4000-8000-000000000003',now-1000),now);const d=m.dashboard(s,now);assert.equal(d.triggers[0].successRate,50);assert.equal(d.triggers[0].status,'Running');assert.equal(m.dashboard(s,now+700000).triggers[0].status,'Unknown')});
test('a later success resolves a failure; acknowledgment alone does not',()=>{const {s,p}=setup();m.applyIntake(s,p,execution('Failed'),now);s.triggers[0].acknowledgedAt=new Date(now).toISOString();assert.equal(m.dashboard(s,now).triggers[0].status,'Failed');m.applyIntake(s,p,execution('Success','00000000-0000-4000-8000-000000000002',now+1000),now+2000);assert.equal(m.dashboard(s,now+2000).triggers[0].status,'Healthy')});
test('old and future telemetry rejected',()=>{const {s,p}=setup();assert.throws(()=>m.applyIntake(s,p,inventory(now+600000),now));assert.throws(()=>m.applyIntake(s,p,execution('Success',undefined,now-31*86400000),now))});
test('completion cannot predate start and duplicate trigger IDs are rejected',()=>{const {s,p}=setup();assert.throws(()=>m.applyIntake(s,p,{...execution(),finishedAt:new Date(now-90000).toISOString()},now));assert.throws(()=>m.applyIntake(s,p,inventory(now+1,[{triggerId,handler:'a',type:'CLOCK'},{triggerId,handler:'b',type:'CLOCK'}]),now))});
test('stale connector never reports healthy',()=>{const {s,p}=setup();m.applyIntake(s,p,execution(),now);assert.equal(m.dashboard(s,now+3*3600000).triggers[0].status,'Unknown')});
test('secrets excluded from dashboard JSON',()=>{const {s,p}=setup();s.accounts[0].refreshToken='secret-refresh';p.connectorHash='secret-hash';const out=JSON.stringify(m.dashboard(s,now));assert.ok(!out.includes('secret-refresh'));assert.ok(!out.includes('secret-hash'));assert.equal(m.dashboard(s,now).accounts[0].connected,true)});
test('encrypted credentials authenticate ciphertext and fail on tampering',()=>{const encrypted=security.encrypt('private-token');assert.ok(!encrypted.includes('private-token'));assert.equal(security.decrypt(encrypted),'private-token');const bytes=Buffer.from(encrypted,'base64url');bytes[15]^=1;assert.throws(()=>security.decrypt(bytes.toString('base64url')))});
test('email escapes metadata and keeps direct sheet/script links',()=>{const {s,p}=setup();p.name='<script>alert(1)</script>';p.sheetId='sheet_123456789';m.applyIntake(s,p,execution('Failed'),now);const out=mail.renderTriggerDigest(s,'https://crm.example.com',now);assert.ok(!out.html.includes('<script>'));assert.ok(out.html.includes('&lt;script&gt;'));assert.ok(out.html.includes('https://docs.google.com/spreadsheets/d/sheet_123456789/edit'));assert.ok(out.html.includes('Execution logs'));assert.equal(out.failures,1)});
test('intake schema rejects unsafe identifiers and excessive batches',()=>{assert.equal(m.ingestSchema.safeParse({...inventory(),scriptId:'<script>'}).success,false);assert.equal(m.ingestSchema.safeParse({...inventory(),triggers:Array(101).fill({triggerId,handler:'a',type:'CLOCK'})}).success,false)});
test('durable local storage survives reload and never uses local fallback in hosted mode',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'trigger-monitor-test-'));sandboxEnv.TRIGGER_MONITOR_TEST_DIR=dir;const store=load('lib/trigger-monitor/store.ts');try{await store.monitorTransaction(s=>s.accounts.push({email:'test@example.com',addedAt:new Date().toISOString()}));assert.ok((await store.readMonitor()).accounts.some(a=>a.email==='test@example.com'));sandboxEnv.VERCEL='1';await assert.rejects(store.readMonitor(),/Shared database/)}finally{delete sandboxEnv.VERCEL;delete sandboxEnv.TRIGGER_MONITOR_TEST_DIR;fs.rmSync(dir,{recursive:true,force:true})}});
const api=load('app/api/trigger-monitor/route.ts'),ingest=load('app/api/trigger-monitor/ingest/route.ts');
function req(body,user,origin='https://crm.example.com'){return {testUser:user,nextUrl:new URL('https://crm.example.com/api/trigger-monitor'),headers:new Headers({origin}),text:async()=>JSON.stringify(body)}}
test('dashboard/API writes require super admin and same origin before storage',async()=>{apiWrites=0;assert.equal((await api.GET(req({},null))).status,403);assert.equal((await api.POST(req({action:'account',email},{role:'admin'}))).status,403);assert.equal((await api.POST(req({action:'account',email},{role:'super_admin'},'https://evil.example'))).status,403);assert.equal(apiWrites,0)});
test('wrong project token cannot ingest; valid telemetry persists',async()=>{const {s,p}=setup();apiState=s;const token='a'.repeat(43);p.connectorHash=security.hash(token);const event=inventory(Date.now());const request={headers:new Headers({authorization:'Bearer '+'b'.repeat(43)}),text:async()=>JSON.stringify(event)};assert.equal((await ingest.POST(request)).status,400);request.headers.set('authorization','Bearer '+token);assert.equal((await ingest.POST(request)).status,200)});
test('connector returns business result and rethrows business failure, without leaking error text',()=>{const gs=fs.readFileSync('docs/trigger-monitor/connector.gs','utf8');const context={console,Date,Utilities:{getUuid:()=> '00000000-0000-4000-8000-000000000001'}};vm.createContext(context);vm.runInContext(gs,context);const events=[];context.crmMonitorIdentity_=()=>({email,scriptId});context.crmMonitorInventory=()=>{};context.crmMonitorDeliver_=e=>events.push({...e});assert.equal(context.crmMonitorRun({triggerUid:'12345'},()=>42),42);assert.equal(events.at(-1).status,'Success');assert.throws(()=>context.crmMonitorRun({triggerUid:'12345'},()=>{throw Error('private-sheet-content')}),/private-sheet-content/);assert.equal(events.at(-1).status,'Failed');assert.ok(!JSON.stringify(events).includes('private-sheet-content'));assert.equal(context.crmMonitorRun(undefined,()=>7),7)});
