const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),ts=require('typescript'),vm=require('node:vm');
function setup(options={}){
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'wa-trigger-test-')),cache={};
 function load(file){file=path.resolve(file);if(cache[file])return cache[file].exports;const module={exports:{}};cache[file]=module;
 const req=id=>{if(id==='@/lib/authz')return {getSessionUser:()=>options.user||null};if(id.startsWith('@/'))return load(id.slice(2)+'.ts');if(id.startsWith('.'))return load(path.resolve(path.dirname(file),id+'.ts'));return require(id)};
 const js=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2021,esModuleInterop:true}}).outputText;
 vm.runInNewContext(js,{module,exports:module.exports,require:req,process:{...process,env:options.env||{},cwd:()=>root},Buffer,console,Date,setTimeout,AbortSignal,fetch:options.fetch});return module.exports}
 return {load,root,cleanup:()=>fs.rmSync(root,{recursive:true,force:true})}
}
const base={name:'Daily Sales',reportId:'daily-sales-report',company:'ALL',recipients:['+919876543210'],consent:true,status:'Draft',time:'09:00',timezone:'Asia/Kolkata',period:'Yesterday',start:'2026-09-16',details:true};
const raw={name:'crm_daily_sales_report_image',language:'en',status:'APPROVED',components:[{type:'HEADER',format:'IMAGE'},{type:'BODY',text:'Report {{1}} for {{2}}'},{type:'FOOTER',text:'Kairali'}]};
test('config rejects Active without consent, invalid dates, unqualified numbers, duplicates and arbitrary templates',()=>{const x=setup();try{const {configSchema}=x.load('lib/whatsapp-triggers/schema.ts');assert.equal(configSchema.safeParse(base).success,true);for(const patch of [{status:'Active',consent:false},{start:'2026-02-29'},{time:'25:00'},{recipients:['9876543210']},{recipients:['+919876543210','+919876543210']},{template:'arbitrary'}])assert.equal(configSchema.safeParse({...base,...patch}).success,false)}finally{x.cleanup()}});
test('only approved English IMAGE templates with exact variables and no interactive components pass',()=>{const x=setup();try{const {normalizeTemplate:n}=x.load('lib/whatsapp-triggers/schema.ts');assert.equal(n(raw).compatible,true);for(const patch of [{status:'PENDING'},{status:'REJECTED'},{language:'hi'},{components:[{type:'HEADER',format:'DOCUMENT'},{type:'BODY',text:'Report {{1}} for {{2}}'}]},{components:[{type:'HEADER',format:'IMAGE'},{type:'BODY',text:'Report {{3}} for {{2}}'}]},{components:[...raw.components,{type:'BUTTONS'}]}])assert.equal(n({...raw,...patch}).compatible,false);assert.equal(n({}),null)}finally{x.cleanup()}});
test('provider refuses requests when API key is absent',async()=>{let calls=0;const x=setup({fetch:async()=>{calls++}});try{await assert.rejects(x.load('lib/whatsapp-triggers/provider.ts').templates(),/not configured/);assert.equal(calls,0)}finally{x.cleanup()}});
test('provider rechecks approval before every send; rejects DOCUMENT and pending templates',async()=>{for(const patch of [{status:'PENDING'},{components:[{type:'HEADER',format:'DOCUMENT'},{type:'BODY',text:'Report {{1}} for {{2}}'}]}]){let sends=0;const x=setup({env:{REDLAVA_API_KEY:'test-only'},fetch:async(url)=>{if(url.endsWith('sendMessage'))sends++;return {ok:true,json:async()=>({results:[{template:{...raw,...patch}}],total:1})}}});try{await assert.rejects(x.load('lib/whatsapp-triggers/provider.ts').sendReport(base,base.recipients[0],'2026-09-15',Buffer.from('image')),/Sending blocked/);assert.equal(sends,0)}finally{x.cleanup()}}});
test('provider uses documented payload, protected headers and demands a message ID',async()=>{let sent;const x=setup({env:{REDLAVA_API_KEY:'test-only',REDLAVA_PHONE_ID:'test-phone'},fetch:async(url,init)=>{assert.equal(init.redirect,'error');assert.equal(init.headers['x-api-key'],'test-only');if(url.endsWith('getTemplates'))return {ok:true,json:async()=>({results:[{template:raw}],total:1})};sent=JSON.parse(init.body);return {ok:true,json:async()=>({waMessageId:'wamid.test'})}}});try{assert.equal(await x.load('lib/whatsapp-triggers/provider.ts').sendReport(base,base.recipients[0],'2026-09-15',Buffer.from('image')),'wamid.test');assert.equal(sent.templateName,raw.name);assert.equal(sent.to,'919876543210');assert.deepEqual(sent.templateVariables,['2026-09-15','All companies']);assert.equal(sent.base64File.name,'daily-sales-report-2026-09-15.jpg')}finally{x.cleanup()}});
test('provider HTTP 200 with error cannot be mistaken for acceptance',async()=>{const x=setup({env:{REDLAVA_API_KEY:'test-only'},fetch:async(url)=>({ok:true,json:async()=>url.endsWith('getTemplates')?{results:[{template:raw}],total:1}:{error:{message:'private provider detail'}}})});try{await assert.rejects(x.load('lib/whatsapp-triggers/provider.ts').sendReport(base,base.recipients[0],'2026-09-15',Buffer.from('image')),e=>!e.message.includes('private provider detail')&&e.message.includes('rejected'))}finally{x.cleanup()}});
test('private storage persists, rollback on exception does not save, hosted writes fail closed',async()=>{const x=setup();try{const s=x.load('lib/whatsapp-triggers/store.ts');await s.transaction(state=>state.triggers.push({...base,id:'test'}));await assert.rejects(s.transaction(state=>{state.triggers=[];throw Error('rollback')}));assert.equal((await s.readState()).triggers.length,1);assert.equal(fs.statSync(path.join(x.root,'.local/whatsapp-triggers/state.json')).mode&0o777,0o600)}finally{x.cleanup()}const hosted=setup({env:{VERCEL:'1'}});try{await assert.rejects(hosted.load('lib/whatsapp-triggers/store.ts').readState(),/Persistent WhatsApp storage/)}finally{hosted.cleanup()}});
test('API denies unsigned and non-super-admin requests; rejects cross-origin writes',async()=>{const {NextRequest}=require('next/server');for(const user of [null,{id:1,role:'admin'}]){const x=setup({user});try{const route=x.load('app/api/whatsapp-trigger-config/route.ts');assert.equal((await route.GET(new NextRequest('http://localhost/api/whatsapp-trigger-config'))).status,403)}finally{x.cleanup()}}const x=setup({user:{id:1,role:'super_admin'}});try{const r=await x.load('app/api/whatsapp-trigger-config/route.ts').POST(new NextRequest('http://localhost/api/whatsapp-trigger-config',{method:'POST',headers:{origin:'https://evil.example'},body:JSON.stringify(base)}));assert.equal(r.status,403)}finally{x.cleanup()}});
test('API saves, reloads, updates with revision, and refuses stale overwrite',async()=>{const {NextRequest}=require('next/server'),x=setup({user:{id:1,role:'super_admin'}});try{const route=x.load('app/api/whatsapp-trigger-config/route.ts'),post=b=>route.POST(new NextRequest('http://localhost/api/whatsapp-trigger-config',{method:'POST',headers:{origin:'http://localhost'},body:JSON.stringify(b)}));const r=await post(base);assert.equal(r.status,200);const {trigger}=await r.json();const change={...base,id:trigger.id,revision:1,name:'Changed'};assert.equal((await post(change)).status,200);assert.equal((await post(change)).status,400);const state=await (await route.GET(new NextRequest('http://localhost/api/whatsapp-trigger-config'))).json();assert.equal(state.triggers[0].name,'Changed');assert.equal(state.schedulerReady,false)}finally{x.cleanup()}});
test('test-send refuses a recipient outside saved consent and duplicates never reach provider twice',async()=>{
 const {NextRequest}=require('next/server');let sends=0;const x=setup({user:{id:1,role:'super_admin'},env:{REDLAVA_API_KEY:'test-only'},fetch:async(url)=>{if(url.endsWith('getTemplates'))return {ok:true,json:async()=>({results:[{template:raw}],total:1})};sends++;return {ok:true,json:async()=>({waMessageId:'wamid.test'})}}});
 try{const store=x.load('lib/whatsapp-triggers/store.ts'),route=x.load('app/api/whatsapp-trigger-config/send/route.ts'),id='11111111-1111-4111-8111-111111111111',requestId='22222222-2222-4222-8222-222222222222';await store.transaction(s=>s.triggers.push({...base,id,revision:1}));const date=x.load('lib/marketing-daily-report.ts').yesterdayIST();const body={id,revision:1,requestId,date,to:'+919876543211',image:Buffer.from([255,216,255,217]).toString('base64')};const post=b=>route.POST(new NextRequest('http://localhost/api/whatsapp-trigger-config/send',{method:'POST',headers:{origin:'http://localhost'},body:JSON.stringify(b)}));assert.equal((await post(body)).status,400);assert.equal(sends,0);body.to=base.recipients[0];assert.equal((await post(body)).status,200);assert.equal((await post(body)).status,400);assert.equal(sends,1);assert.equal((await store.readState()).runs[0].status,'Accepted')
 }finally{x.cleanup()}
});
async function withScheduler(fn){const x=setup();try{const store=x.load('lib/whatsapp-triggers/store.ts'),runner=x.load('lib/whatsapp-triggers/dispatch.ts'),now=Date.parse('2026-09-16T03:30:00Z');await store.transaction(s=>s.triggers.push({...base,id:'scheduled-test',revision:1,status:'Active',nextRun:new Date(now).toISOString()}));await fn({store,runner,now})}finally{x.cleanup()}}
test('daily worker reserves once, sends yesterday IST, advances next run',()=>withScheduler(async({store,runner,now})=>{let sends=0;const io={build:async(c,date)=>{assert.equal(date,'2026-09-15');return Buffer.from('jpeg')},send:async()=>{sends++;return 'wamid.test'}};await runner.dispatchDue(now,io);await runner.dispatchDue(now,io);assert.equal(sends,1);const s=await store.readState();assert.equal(s.runs.length,1);assert.equal(s.runs[0].status,'Accepted');assert.equal(s.triggers[0].nextRun,'2026-09-17T03:30:00.000Z')}));
test('missed schedules skip without rendering or sending',()=>withScheduler(async({store,runner,now})=>{await runner.dispatchDue(now+3600000,{build:async()=>{throw Error('must not render')},send:async()=>{throw Error('must not send')}});assert.equal((await store.readState()).runs[0].status,'Skipped')}));
test('pause or revision change while image is preparing prevents sends',()=>withScheduler(async({store,runner,now})=>{let sends=0;await runner.dispatchDue(now,{build:async()=>{await store.transaction(s=>s.triggers[0].revision++);return Buffer.from('jpeg')},send:async()=>{sends++;return 'id'}});assert.equal(sends,0);assert.equal((await store.readState()).runs[0].status,'Skipped')}));
test('uncertain provider acceptance pauses schedule and is never retried',()=>withScheduler(async({store,runner,now})=>{let sends=0;const io={build:async()=>Buffer.from('jpeg'),send:async()=>{sends++;throw Error('timeout')}};await runner.dispatchDue(now,io);await runner.dispatchDue(now+86400000,io);assert.equal(sends,1);const s=await store.readState();assert.equal(s.triggers[0].status,'Paused');assert.equal(s.runs[0].status,'Unknown')}));
test('interrupted reservations become Unknown, never automatic resend',()=>withScheduler(async({store,runner,now})=>{await store.transaction(s=>s.runs.push({id:'old-run',triggerId:'scheduled-test',scheduledAt:new Date(now-86400000).toISOString(),startedAt:new Date(now-3600000).toISOString(),status:'Sending'}));let sends=0;await runner.dispatchDue(now,{build:async()=>Buffer.from('jpeg'),send:async()=>{sends++;return 'id'}});assert.equal(sends,0);assert.equal((await store.readState()).triggers[0].status,'Paused')}));
test('renderer failure records Failed before any provider call',()=>withScheduler(async({store,runner,now})=>{let sends=0;await runner.dispatchDue(now,{build:async()=>{throw Error('render failure')},send:async()=>{sends++;return 'id'}});assert.equal(sends,0);assert.equal((await store.readState()).runs[0].status,'Failed')}));
test('activation is rejected without worker heartbeat or provider configuration',async()=>{const {NextRequest}=require('next/server'),x=setup({user:{id:1,role:'super_admin'}});try{const route=x.load('app/api/whatsapp-trigger-config/route.ts'),r=await route.POST(new NextRequest('http://localhost/api/whatsapp-trigger-config',{method:'POST',headers:{origin:'http://localhost'},body:JSON.stringify({...base,status:'Active'})}));assert.equal(r.status,400);assert.match((await r.json()).error,/healthy image worker/);assert.equal((await x.load('lib/whatsapp-triggers/store.ts').readState()).triggers.length,0)}finally{x.cleanup()}});
test('worker readiness expires and rejects future heartbeat timestamps',()=>{const x=setup();try{const {workerReady}=x.load('lib/whatsapp-triggers/schedule.ts'),now=Date.now();assert.equal(workerReady({rendererReady:true,heartbeat:new Date(now-1000).toISOString()},now),true);assert.equal(workerReady({rendererReady:true,heartbeat:new Date(now-120001).toISOString()},now),false);assert.equal(workerReady({rendererReady:true,heartbeat:new Date(now+1000).toISOString()},now),false)}finally{x.cleanup()}});
