'use client'

import { useCallback, useEffect, useState } from 'react'
import Link from 'next/link'
import { useRouter, useSearchParams } from 'next/navigation'
import { Activity, AlertTriangle, CheckCircle2, Clock3, Download, ExternalLink, Mail, Plus, RefreshCw, Search, Settings } from 'lucide-react'
import { DashboardLayout } from '@/components/dashboard-layout'
import { useAuth } from '@/hooks/use-auth'
import type { Dashboard } from '@/lib/trigger-monitor/model'
import type { Trigger } from '@/lib/email-triggers/schema'

type Data = Dashboard & { oauthReady: boolean; cronConfigured: boolean; googleSetup: { ready: boolean; missing: string[]; callbackUrl: string | null } }
type EmailState = { triggers: Trigger[]; smtpReady: boolean; workerReady: boolean }
const control='rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-800 disabled:opacity-50'
const primary='rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-700 disabled:opacity-50'
const stamp=(s?:string)=>s?new Date(s).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}):'Not available'
async function request(url:string,body?:unknown){
 const res=await fetch(url,{cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})})
 const data=await res.json();if(!res.ok)throw Error(data.error||'Request failed');return data
}
function GoogleLink({url,children}:{url?:string|null;children:React.ReactNode}){return url?<a href={url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-sm font-medium text-indigo-700 hover:underline">{children}<ExternalLink size={13}/></a>:<span className="text-sm text-slate-400">{children}: unavailable</span>}
export default function TriggerManagement(){
 const router=useRouter(),params=useSearchParams()
 const {user,isLoading}=useAuth(),isAdmin=['super_admin','super admin'].includes(String(user?.role||'').trim().toLowerCase())
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(()=>params.get('connection')==='success'?'Google account authorized. Review discovered projects and install connectors.':params.get('connection')==='failed'?'Google connection failed. Check consent, selected account and OAuth callback configuration.':''),[busy,setBusy]=useState(false)
 const [tab,setTab]=useState<'dashboard'|'projects'|'email'>('dashboard'),[email,setEmail]=useState(''),[account,setAccount]=useState('all'),[query,setQuery]=useState(''),[status,setStatus]=useState('all')
 const [selected,setSelected]=useState<string|null>(params.get('trigger')),[assignee,setAssignee]=useState(''),[projectEmail,setProjectEmail]=useState('sysadmin@kairali.com'),[scriptId,setScriptId]=useState(''),[projectName,setProjectName]=useState('')
 const [token,setToken]=useState<{key:string;value:string}|null>(null),[preview,setPreview]=useState(''),[recipients,setRecipients]=useState(''),[time,setTime]=useState('09:00')
 const [emailState,setEmailState]=useState<EmailState|null>(null)
 const refresh=useCallback(async()=>{try{setData(await request('/api/trigger-monitor'));setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to load dashboard')}},[])
 useEffect(()=>{
  if(!isAdmin)return
  let cancelled=false
  request('/api/trigger-monitor').then(value=>{if(!cancelled)setData(value)}).catch(e=>{if(!cancelled)setError(e.message)})
  const timer=setInterval(()=>{if(!document.hidden)void refresh()},30000)
  return()=>{cancelled=true;clearInterval(timer)}
 },[isAdmin,refresh])
 useEffect(()=>{
  if(!isAdmin||tab!=='email')return
  let cancelled=false
  request('/api/email-trigger-config').then((state:EmailState)=>{
   if(cancelled)return
   setEmailState(state)
   const saved=state.triggers.find(t=>t.reportId==='trigger-health-digest')
   if(saved){setRecipients(saved.to);setTime(saved.time)}
  }).catch(e=>{if(!cancelled)setError(e.message)})
  return()=>{cancelled=true}
 },[isAdmin,tab])
 async function perform(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn();await refresh()}catch(e){setError(e instanceof Error?e.message:'Operation failed')}finally{setBusy(false)}}
 async function connect(address:string){await perform(async()=>{const result=await request('/api/trigger-monitor/connect',{email:address});window.location.assign(result.url)})}
 const all=data?.triggers||[],active=all.filter(t=>t.status!=='Removed'),success=active.reduce((n,t)=>n+t.success,0),failed=active.reduce((n,t)=>n+t.failed,0)
 const filtered=all.filter(t=>(account==='all'||t.email===account)&&(status==='all'||t.status===status)&&[t.email,t.sheetName,t.projectName,t.handler,t.triggerId].join(' ').toLowerCase().includes(query.toLowerCase()))
 const detail=all.find(t=>t.key===selected)
 async function saveDigest(activate=false){await perform(async()=>{
  const state=await request('/api/email-trigger-config')
  const existing=state.triggers.find((t:{reportId:string})=>t.reportId==='trigger-health-digest')
  setEmailState(state)
  if(activate&&!recipients.trim())throw Error('Enter developer email recipients before activation.')
  if(activate&&(!state.smtpReady||!state.workerReady))throw Error('SMTP and the background email worker must be ready before activation.')
  const result=await request('/api/email-trigger-config',{name:'Daily Trigger Health & Failure Alert',reportId:'trigger-health-digest',source:'Daily Trigger Health & Failure Alert',template:'Daily Trigger Health & Failure Alert',department:'IT',company:'All companies',cc:'',bcc:'',subject:'[Trigger Health] Daily failures and status — {{report_date}}',body:'',bodyType:'Full report in email body',intro:'',closing:'',period:'Today',reportDetail:'Full report',interval:'6',weekday:'Monday',monthday:'1',start:new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'}),end:'',attachment:'None',mode:'Same email to all recipients',condition:'Always send',retry:'No retries',missed:'Skip missed run',replyTo:'',...existing,to:recipients,time,custom:time,frequency:'Daily',timezone:'Asia/Kolkata',status:activate?'Active':existing?.status||'Draft'})
  setEmailState({...state,triggers:[...state.triggers.filter((t:Trigger)=>t.reportId!=='trigger-health-digest'),result.trigger]})
  if(activate)setNotice(`Daily email activated. Next scheduled run: ${stamp(result.trigger.nextRun)}.`)
  else router.push('/settings/automation/email-triggers?report=trigger-health-digest')
 })}
 if(isLoading)return <div className="p-8">Loading account…</div>
 if(!isAdmin)return <div className="p-8">Super administrator access required.</div>
 return <DashboardLayout><div className="space-y-6">
  <section className="rounded-xl bg-gradient-to-r from-blue-600 via-blue-700 to-indigo-700 p-6 text-white shadow-lg sm:p-8"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-4"><div className="rounded-xl border border-white/30 bg-white/20 p-3"><Activity size={30}/></div><div><h1 className="text-2xl font-bold sm:text-3xl">Trigger Management</h1><p className="mt-1 text-sm text-blue-100">Google Sheets trigger health, ownership & daily developer alerts</p></div></div><button disabled={busy} onClick={()=>perform(refresh)} className="flex items-center gap-2 rounded-lg border border-white/30 bg-white/10 px-4 py-2 text-sm"><RefreshCw size={16}/> Refresh</button></div><p className="mt-5 text-xs text-blue-100">Settings / Automation / Trigger Management · Times in Asia/Kolkata · Last 24 hours</p></section>
  {error&&<div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</div>}
  {notice&&<div role="status" className="rounded-lg border border-indigo-200 bg-indigo-50 p-4 text-sm text-indigo-900">{notice}</div>}
  <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><h2 className="flex items-center gap-2 border-b bg-gradient-to-r from-indigo-50 to-white px-5 py-3 font-semibold"><Mail size={18}/>Add Email Account & Discover Triggers</h2><form className="flex flex-wrap gap-3 p-5" onSubmit={e=>{e.preventDefault();void perform(async()=>{await request('/api/trigger-monitor',{action:'account',email});setEmail('');setNotice('Account added. Select Connect Google to authorize discovery.');setTab('projects')})}}><input aria-label="New Google account email" type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="Enter Google email ID" className={`${control} min-w-0 flex-1`}/><button disabled={busy} className={primary}><Plus className="mr-1 inline" size={16}/>Add account</button></form><p className="px-5 pb-4 text-xs text-slate-500">Google consent discovers accessible standalone Apps Script projects. Sheet-bound scripts require their script ID once; exact trigger inventory and results require the project connector.</p></section>
  <div className="grid grid-cols-2 gap-4 xl:grid-cols-4">{[
   ['Monitored triggers',data?active.length:'—',`${data?.accounts.length||0} registered accounts`,Activity],
   ['Failing triggers',data?active.filter(t=>t.status==='Failed').length:'—',`${active.filter(t=>t.status==='Unknown').length} unknown / missing telemetry`,AlertTriangle],
   ['Execution success',data&&success+failed?`${(success/(success+failed)*100).toFixed(1)}%`:'—',`${success} successful completed runs`,CheckCircle2],
   ['Execution failure',data&&success+failed?`${(failed/(success+failed)*100).toFixed(1)}%`:'—',`${failed} failed completed runs`,Clock3],
  ].map(([label,value,sub,Icon],i)=>{const MetricIcon=Icon as typeof Activity;return <div key={String(label)} className={`rounded-xl border border-slate-200 border-t-4 bg-white p-4 shadow-sm ${i===1||i===3?'border-t-red-500':'border-t-indigo-500'}`}><div className="flex items-center justify-between text-xs text-slate-500"><span>{String(label)}</span><MetricIcon size={17}/></div><p className="my-2 text-3xl font-bold text-slate-900">{String(value)}</p><p className="text-xs text-slate-500">{String(sub)}</p></div>})}</div>
  <div className="grid gap-3 lg:grid-cols-3">{data?.accounts.map(a=><button key={a.email} aria-pressed={account===a.email} onClick={()=>{setAccount(account===a.email?'all':a.email);setTab('dashboard')}} className={`break-all rounded-xl border bg-white p-4 text-left shadow-sm ${account===a.email?'border-indigo-500 ring-1 ring-indigo-500':'border-slate-200'}`}><span className="text-sm font-semibold">{a.email}</span><p className="mt-2 text-sm">{active.filter(t=>t.email===a.email).length} triggers · <span className="text-red-700">{active.filter(t=>t.email===a.email&&t.status==='Failed').length} failed</span></p><p className="mt-1 text-xs text-slate-500">{a.connected?'Google authorized':'Google not connected'} · {data.projects.filter(p=>p.email===a.email&&p.lastInventory).length} projects reporting</p></button>)}</div>
  <nav className="flex flex-wrap gap-2 border-b pb-3" aria-label="Trigger management sections">{[['dashboard','Trigger Dashboard'],['projects','Accounts & Project Setup'],['email','Daily Email Configuration']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id as typeof tab)} className={tab===id?primary:control}>{label}</button>)}</nav>
  {tab==='dashboard'&&<>
   <div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">Failures first. No observed execution means Unknown. Rates exclude Running / Unknown outcomes. {data?.truncatedBefore?'Retention limit reached: metrics cover retained events only.':''}</div>
   <section className="rounded-xl border bg-white p-4"><div className="mb-3 flex items-center gap-2 font-semibold"><Search size={17}/>Filters & Search</div><div className="flex flex-wrap gap-3"><input className={`${control} min-w-0 flex-1`} aria-label="Search triggers" placeholder="Sheet, function, trigger ID or email…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Account filter" className={control} value={account} onChange={e=>setAccount(e.target.value)}><option value="all">All accounts</option>{data?.accounts.map(a=><option key={a.email}>{a.email}</option>)}</select><select aria-label="Status filter" className={control} value={status} onChange={e=>setStatus(e.target.value)}>{['all','Failed','Unknown','Running','Healthy','Removed'].map(s=><option key={s} value={s}>{s==='all'?'All statuses':s}</option>)}</select></div></section>
   <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[950px] text-left text-sm"><thead className="bg-indigo-50 text-xs uppercase text-slate-600"><tr>{['Sheet / Function','Trigger creator','Status','Success / Failed (24h)','Last run / Duration','Actions'].map(h=><th key={h} className="p-4">{h}</th>)}</tr></thead><tbody>{filtered.map(t=><tr key={t.key} className="border-t hover:bg-slate-50"><td className="p-4"><div className="font-semibold">{t.sheetName||t.projectName}</div><div className="mt-1 text-xs text-slate-500">{t.handler}</div></td><td className="p-4 text-xs">{t.email}</td><td className="p-4"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${t.status==='Failed'?'bg-red-100 text-red-800':t.status==='Healthy'?'bg-emerald-100 text-emerald-800':'bg-amber-100 text-amber-900'}`}>{t.status}</span>{t.acknowledgedAt&&<div className="mt-2 text-xs text-slate-500">Acknowledged</div>}</td><td className="p-4">{t.successRate===null?'—':`${t.successRate.toFixed(1)}% / ${(100-t.successRate).toFixed(1)}%`}<div className="text-xs text-slate-500">{t.success} passed · {t.failed} failed</div></td><td className="p-4 text-xs">{stamp(t.latest?.startedAt)}<div className="mt-1 text-slate-500">{t.latest?.durationMs===undefined?'—':`${(t.latest.durationMs/1000).toFixed(1)}s`}</div></td><td className="p-4"><button className="font-semibold text-indigo-700" onClick={()=>{setSelected(t.key);setAssignee(t.assignee||'')}}>Details</button></td></tr>)}{!filtered.length&&<tr><td colSpan={6} className="p-12 text-center text-slate-500">{!data?'Loading monitoring state…':all.length?'No triggers match these filters.':'No trigger inventory yet. Connect accounts and install project connectors in Accounts & Project Setup.'}</td></tr>}</tbody></table></div><p className="text-xs text-slate-500">{filtered.length} of {all.length} triggers · KPI totals cover all active accounts · Auto-refresh every 30 seconds</p>
   {detail&&<section className="rounded-xl border border-indigo-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><h2 className="text-lg font-semibold">{detail.sheetName||detail.projectName} — Trigger details</h2><button className={control} onClick={()=>setSelected(null)}>Close</button></div><div className="mt-4 grid gap-4 md:grid-cols-2">{[
    ['Creator / execution identity',detail.email],['Sheet owner',detail.sheetOwner||'Unavailable / shared drive'],['Trigger ID',detail.triggerId],['Function / event',`${detail.handler} / ${detail.type}`],['Created date',detail.createdAt?stamp(detail.createdAt):'Not exposed for imported Google triggers'],['First discovered',stamp(detail.firstSeen)],['Consecutive failures',String(detail.consecutiveFailures)],['Last inventory',stamp(detail.lastSeen)],['Failure reason',detail.reason],['Suggested resolution',detail.solution],['Schedule / next run','Google does not expose existing trigger schedule metadata; inspect the script Triggers page.'],['Inventory health',detail.stale?'Stale: check connector heartbeat':'Reporting'],
   ].map(([k,v])=><div key={k}><p className="text-xs text-slate-500">{k}</p><p className="mt-1 break-words text-sm">{v}</p></div>)}</div><div className="my-5 flex flex-wrap gap-5"><GoogleLink url={detail.sheetUrl}>Open sheet</GoogleLink><GoogleLink url={detail.scriptUrl}>Open script</GoogleLink><GoogleLink url={detail.logsUrl}>Execution logs</GoogleLink></div><form className="flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();void perform(async()=>{await request('/api/trigger-monitor',{action:'assign',key:detail.key,assignee});setNotice('Developer assignment saved.')})}}><input aria-label="Assigned developer email" type="email" placeholder="Developer email" value={assignee} onChange={e=>setAssignee(e.target.value)} className={control}/><button disabled={busy} className={primary}>Assign developer</button><button disabled={busy||detail.status!=='Failed'} type="button" className={control} onClick={()=>perform(async()=>{await request('/api/trigger-monitor',{action:'acknowledge',key:detail.key});setNotice('Acknowledged. Status stays failed until a later successful execution.')})}>Acknowledge failure</button></form><h3 className="mb-2 mt-6 font-semibold">Recent executions</h3><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr><th className="p-2">Started (IST)</th><th className="p-2">Result</th><th className="p-2">Duration</th><th className="p-2">Run ID</th></tr></thead><tbody>{detail.history.map(r=><tr key={r.key} className="border-t"><td className="p-2">{stamp(r.startedAt)}</td><td className="p-2">{r.status==='Running'&&Date.parse(data?.generatedAt||r.startedAt)-Date.parse(r.startedAt)>600000?'Unknown (no completion)':r.status}</td><td className="p-2">{r.durationMs===undefined?'—':`${(r.durationMs/1000).toFixed(1)}s`}</td><td className="p-2">{r.runId}</td></tr>)}</tbody></table></div></section>}
  </>}
  {tab==='projects'&&data&&!data.oauthReady&&<section className="space-y-3 rounded-xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-semibold">Complete Google connection setup</h2><p className="text-sm">Missing server configuration: {data.googleSetup.missing.join(', ')}. Add credentials securely in the staging project environment variables, then redeploy.</p><p className="text-sm">Google Cloud OAuth client type: Web application. Enable Google Drive API and configure External audience for accounts across your domains and Gmail. In Testing mode, add all three accounts as test users.</p><label className="block text-sm">Authorized redirect URI<input readOnly aria-label="Google OAuth redirect URI" value={data.googleSetup.callbackUrl||'Configure application URL first'} className={`${control} mt-1 w-full font-mono`}/></label><p className="text-sm">After server setup, each account owner must click Connect Google and grant consent. Project connectors are still required to report trigger execution results.</p><a className="inline-block text-sm font-semibold text-indigo-700 underline" href="https://console.cloud.google.com/auth/clients" target="_blank" rel="noopener noreferrer">Open Google Cloud OAuth clients</a></section>}
  {tab==='projects'&&<div className="space-y-5"><section className="rounded-xl border bg-white p-5"><h2 className="mb-3 font-semibold">Google account connections</h2>{!data?.oauthReady&&<p className="mb-3 text-sm text-amber-800">Google OAuth configuration is incomplete. Set credentials, application URL and token encryption key before connecting.</p>}{data?.accounts.map(a=><div key={a.email} className="flex flex-wrap items-center justify-between gap-3 border-t py-4"><div><p className="break-all text-sm font-semibold">{a.email}</p><p className="text-xs text-slate-500">Last scan: {stamp(a.lastScan)} {a.scanCursor?'· More pages pending':''}</p>{a.scanError&&<p className="text-xs text-red-700">{a.scanError}</p>}</div><div className="flex flex-wrap gap-2"><button disabled={busy||!data.oauthReady} className={primary} onClick={()=>connect(a.email)}>{a.connected?'Reconnect':'Connect Google'}</button><button disabled={busy||!a.connected} className={control} onClick={()=>perform(async()=>{const r=await request('/api/trigger-monitor',{action:'scan',email:a.email});setNotice(`${r.discovered} projects scanned. ${r.more?'Next page will be scanned automatically.':'Standalone discovery complete; register bound projects below.'}`)})}>Scan projects</button>{a.connected&&<button disabled={busy} className={control} onClick={()=>{if(window.confirm('Disconnect this account and revoke all its CRM project connector tokens?'))void perform(async()=>{await request('/api/trigger-monitor',{action:'disconnect',email:a.email});setNotice('Disconnected locally. Google access can also be revoked in your Google account security settings.')})}}>Disconnect</button>}</div></div>)}<p className="mt-3 text-xs text-slate-500">Discovery heartbeat: {stamp(data?.heartbeat)} · {data?.cronConfigured?'Cron secret configured':'Cron secret missing'} · Scans run every 15 minutes after deployment.</p></section>
   <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Register a sheet-bound or missing project</h2><p className="my-2 text-xs text-slate-500">In the sheet: Extensions → Apps Script → Project Settings → Script ID. Register each creator account separately.</p><form onSubmit={e=>{e.preventDefault();void perform(async()=>{await request('/api/trigger-monitor',{action:'project',email:projectEmail,scriptId:scriptId.trim(),name:projectName});setScriptId('');setProjectName('');setNotice('Project registered. Generate its connector token below.')})}} className="mt-4 grid gap-3 md:grid-cols-2"><select aria-label="Project account" className={control} value={projectEmail} onChange={e=>setProjectEmail(e.target.value)}>{data?.accounts.map(a=><option key={a.email}>{a.email}</option>)}</select><input required className={control} aria-label="Project name" placeholder="Project / sheet name" value={projectName} onChange={e=>setProjectName(e.target.value)}/><input required className={control} aria-label="Script ID" placeholder="Apps Script project ID" value={scriptId} onChange={e=>setScriptId(e.target.value)}/><button disabled={busy} className={primary}>Register project</button></form></section>
   <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Project connectors</h2><ol className="my-4 list-inside list-decimal space-y-2 text-sm text-slate-600"><li>Download the connector and add it to the Apps Script project.</li><li>Generate the project token below. Run <code>crmMonitorConfigure</code> as the trigger creator and grant Google consent.</li><li>Wrap each existing trigger handler using <code>crmMonitorRun(e, function () &#123; /* existing code */ &#125;)</code>. Keep existing trigger names and schedules.</li><li>Hourly inventory and each wrapped execution report automatically. Unwrapped executions remain Unknown.</li></ol><a href="/api/trigger-monitor/connector" className="inline-flex items-center gap-2 text-sm font-semibold text-indigo-700"><Download size={16}/>Download Apps Script connector</a>{data?.projects.map(p=><div key={p.key} className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t pt-4"><div className="min-w-0"><p className="font-semibold">{p.name}</p><p className="break-all text-xs text-slate-500">{p.email} · {p.scriptId}</p><p className="text-xs text-slate-500">Inventory: {stamp(p.lastInventory)}</p></div><button disabled={busy} className={control} onClick={()=>{if(p.connectorConfigured&&!window.confirm('Rotate this project token? The old connector will stop until reconfigured.'))return;void perform(async()=>{const r=await request('/api/trigger-monitor',{action:'connector',key:p.key});setToken({key:p.key,value:r.token})})}}>{p.connectorConfigured?'Rotate token':'Generate token'}</button></div>)}{token&&<div className="mt-5 rounded-lg border border-amber-200 bg-amber-50 p-4"><p className="break-all text-sm font-semibold">One-time token for {token.key}</p><p className="my-2 text-xs">Keep private. Paste into the connector prompt. It is not stored in readable form on the server.</p><input aria-label="One-time connector token" readOnly value={token.value} className={`${control} w-full font-mono`}/><button className={`${control} mt-2`} onClick={()=>setToken(null)}>Hide token</button></div>}</section></div>}
  {tab==='email'&&<section className="rounded-xl border bg-white p-5"><h2 className="mb-3 font-semibold">Email activation readiness</h2><div className="grid gap-3 text-sm sm:grid-cols-3"><p>SMTP: {emailState?(emailState.smtpReady?'Configured':'Missing configuration'):'Checking…'}</p><p>Email worker: {emailState?(emailState.workerReady?'Ready':'No recent heartbeat'):'Checking…'}</p><p>Daily alert: {emailState?.triggers.find(t=>t.reportId==='trigger-health-digest')?.status||'Not configured'}</p></div><p className="mt-3 text-xs text-slate-500">Next run: {stamp(emailState?.triggers.find(t=>t.reportId==='trigger-health-digest')?.nextRun||undefined)}. Missing Google telemetry is reported as incomplete coverage, never as a successful execution.</p></section>}
  {tab==='email'&&<section className="space-y-5 rounded-xl border bg-white p-5"><h2 className="flex items-center gap-2 text-lg font-semibold"><Settings size={20}/>Daily Trigger Health & Failure Alert</h2><p className="text-sm text-slate-600">All statuses, failures first; creator, sheet owner, trigger ID, execution results, reason, suggested fix and direct sheet/script/log links. Uses the CRM sender and existing email scheduler.</p><div className="grid gap-4 md:grid-cols-2"><label className="text-sm">Developer recipients<input type="text" value={recipients} onChange={e=>setRecipients(e.target.value)} placeholder="developer@company.com, team@company.com" className={`${control} mt-1 w-full`}/></label><label className="text-sm">Daily time · Asia/Kolkata<input type="time" value={time} onChange={e=>setTime(e.target.value)} className={`${control} mt-1 w-full`}/></label></div><div className="flex flex-wrap gap-3"><button className={primary} disabled={busy} onClick={()=>saveDigest()}>Save & open Email Configuration</button><button className={primary} disabled={busy||!emailState?.smtpReady||!emailState?.workerReady||!recipients.trim()} onClick={()=>saveDigest(true)}>Activate daily email</button><button className={control} disabled={busy} onClick={()=>perform(async()=>{const res=await fetch('/api/trigger-monitor/preview',{cache:'no-store'});if(!res.ok)throw Error('Email preview unavailable');setPreview(await res.text())})}>Preview live email</button><Link className={control} href="/settings/automation/email-triggers?report=trigger-health-digest">Schedule & delivery history</Link></div><p className="text-xs text-slate-500">Activate here once recipients, SMTP and the email worker are ready. Existing recipients and schedule load automatically. The scheduler records accepted, failed and uncertain delivery outcomes.</p>{preview&&<iframe title="Daily trigger email preview" srcDoc={preview} sandbox="" className="h-[700px] w-full rounded-lg border"/>}</section>}
 </div></DashboardLayout>
}
